export { ArticleDetails } from './ui/ArticleDetails/ArticleDetails'
export type { Article } from './model/types/article'
export type { articleDetailsSchema } from './model/types/articleDetailsSchema'
export { articleDetailsData } from './model/selectors/articleDetails'
export { articleDetailsReducer } from './model/slice/articleDetailsSlice'